config/routes.rb
Rails.application.routes.draw do
  resources :company_mops
  resources :mops
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  resources :comments
  resources :deliveries do
    collection do
      get :deliver_all
    end
  end
  
  resources :mats
  
  resources :company_mats
 root :to => 'pages#dashboard'
  resources :companies

resources :pages do 
	collection do 
		get :dashboard
		get :new_contracts
		get :one_day
  end
end
resources :users, only: [:new, :create, :show]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'

   get 'log_out', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/delivery.rb
class Delivery < ApplicationRecord

	def name 
		"Delivery #" + self.id.to_s
	end
	def get_obj 
		

		klass = Object.const_get self.klass

		klass.find(self.klass_id)

	end

	def comments
		Comment.where(klass: self.class.name, klass_id: self.id ).order(created_at: :asc)
 
	end

	def got_comments? 
		if Comment.where(klass: self.class.name, klass_id: self.id ).count > 0 
			true
		else
			false
		end

	end

	def get_comment
		cmt = Comment.where(klass: self.class.name, klass_id: self.id ).order(created_at: :desc).first
		str = cmt.comment + " | " + cmt.created_at.strftime("%d-%m-%y %H:%M")
		return str
	end




	def company 

	end

end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
   @comment = Comment.new
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        is_delivered?
        format.html { redirect_to "/pages/dashboard", notice: 'Delivery was successfully created.' }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        is_delivered?

        format.html { redirect_to "/pages/one_day", notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deliver_all
    c = Company.find(params[:company_id])
    date = DateTime.parse(params[:date])
    d = Delivery.where(company_id: params[:company_id].to_i).where(delivery: date)
    d.update_all(delivered: true, delivered_date: DateTime.now)


    redirect_to request.referrer

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def delivery_params
      params.require(:delivery).permit(:klass, :klass_id, :pack_date, :delivery, :delivered_date, :change_amount, :notify, :commet_id, :delivered, :company_id)
    end

    def is_delivered?
      if @delivery.delivered?
        @delivery.delivered_date = Time.now
      else
        @delivery.delivered_date = nil
    end
    @delivery.save!
  end

end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_with(model: delivery, local: true) do |form| %>
  <% if delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
        <% delivery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :klass %>
    <%= form.text_field :klass %>
  </div>

  <div class="field">
    <%= form.label :klass_id %>
    <%= form.number_field :klass_id %>
  </div>

  <div class="field">
    <%= form.label :pack_date %>
    <%= form.date_select :pack_date %>
  </div>

  <div class="field">
    <%= form.label :delivery %>
    <%= form.date_select :delivery %>
  </div>

  <div class="field">
    <%= form.label :delivered_date %>
    <%= form.date_select :delivered_date %>
  </div>

  <div class="field">
    <%= form.label :change_amount %>
    <%= form.number_field :change_amount %>
  </div>

  <div class="field">
    <%= form.label :notify %>
    <%= form.check_box :notify %>
  </div>

  <div class="field">
    <%= form.label :commet_id %>
    <%= form.number_field :commet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Show', @delivery %> |
<%= link_to 'Back', deliveries_path %>

app/views/deliveries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveries</h1>

<table>
  <thead>
    <tr>
      <th>Klass</th>
      <th>Klass</th>
      <th>Pack date</th>
      <th>Delivery</th>
      <th>Delivered date</th>
      <th>Change amount</th>
      <th>Notify</th>
      <th>Commet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.klass %></td>
        <td><%= delivery.klass_id %></td>
        <td><%= delivery.pack_date %></td>
        <td><%= delivery.delivery %></td>
        <td><%= delivery.delivered_date %></td>
        <td><%= delivery.change_amount %></td>
        <td><%= delivery.notify %></td>
        <td><%= delivery.commet_id %></td>
        <td><%= link_to 'Show', delivery %></td>
        <td><%= link_to 'Edit', edit_delivery_path(delivery) %></td>
        <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery', new_delivery_path %>

app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Back', deliveries_path %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"> Delivery # <%= @delivery.id %> </h1>
</div>
<hr/>



<hr/>

<% @delivery.comments.each do |c| %>
<div class="row-fluid">
<div class="col-xl-6 col-lg-10 col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Karl Andre Oddsen <small style="float:right"><%= c.created_at.strftime("%d-%m-%Y %H:%M") %></small></h6>
              </div>
              <div class="card-body py-1">
                    <p class="text-italic">
                      <%= c.comment %>
                    </p>
                    
              </div>
              <div class="card-footer">
                <i class="far fa-edit"></i>
                <%= link_to "Edit", edit_comment_path(c) %> 
                <i class="far fa-minus-square"></i>
                <%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
                    
                  
          </div>
      </div>
</div>

<% end %>
  

<div class="row-fluid">
  <div class="col-xl-4 col-lg-10 col-md-12">
              <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text"> Add comment</h6>
                </div>
                <div class="card-body py-1" >
                   <%= form_for @comment do |form| %>
                    <%= form.hidden_field :klass, :value => @delivery.class.name  %>
                    <%= form.hidden_field :klass_id, :value => @delivery.id  %>
                    <%= form.text_area :comment, cols: 65, rows: 3, placeholder: "Write comment here" %> 
                      
                </div>
                <div class="card-footer">
                 <%= form.submit "Comment", :class => "btn btn-primary btn-block"  %>
                 <% end %> 
                </div>
                      
                    
            </div>
    </div>
</div>