config/routes.rb
Rails.application.routes.draw do
  resources :company_mops
  resources :mops
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  resources :comments
  resources :deliveries do
    collection do
      get :deliver_all
    end
  end
  
  resources :mats
  
  resources :company_mats
 root :to => 'pages#dashboard'
  resources :companies

resources :pages do 
	collection do 
		get :dashboard
		get :new_contracts
		get :one_day
  end
end
resources :users, only: [:new, :create, :show]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'

   get 'log_out', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_dashboard_header.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"> Dashboard  </h1>

    
</div>
<hr/>
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h4 mb-0 text-gray-800"> Livefeed <small>Last update: <%= (DateTime.now + 1.hour).strftime("%H:%M:%S") %> </small> </h1>
</div>
<div class="row">
       
            <div class="col-xl-3 col-lg-6 col-md-12 mb-4">
             <%= link_to "/pages/one_day?done=true&day=today" do %>
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-md font-weight-bold text-success text-uppercase mb-1">Deliveries made today</div>
                      <div class="h4 mb-0 font-weight-bold text-gray-800"><%= @today.count %></div>
                    </div>
                    <div class="col-auto">
                      
                      <i class="fas fa-truck fa text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>

            <div class="col-xl-3 col-lg-6 col-md-12 mb-4">
              <%= link_to "/pages/one_day?done=false&day=today" do %>
              <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-md font-weight-bold text-success text-uppercase mb-1">Deliveries remaining today</div>
                      <div class="h4 mb-0 font-weight-bold text-gray-800"><%= @today_remain.count %></div>
                    </div>
                    <div class="col-auto">
                      
                      <i class="fas fa-truck fa text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
     
           <div class="col-xl-3 col-lg-6 col-md-12 mb-4">
             <%= link_to "/pages/one_day?done=false&day=tomorrow" do %>
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-md font-weight-bold text-success text-uppercase mb-1">Deliveries for tomorrow</div>
                      <div class="h4 mb-0 font-weight-bold text-gray-800"><%= @tomorrow.count %></div>
                    </div>
                    <div class="col-auto">
                      
                      <i class="fas fa-truck fa text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
           <div class="col-xl-3 col-lg-6 col-md-12 mb-4">
              <%= link_to "/pages/dashboard" do %>
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-md font-weight-bold text-success text-uppercase mb-1">Deliveries for this week</div>
                      <div class="h4 mb-0 font-weight-bold text-gray-800"><%= @this_week_true.count %></div>
                    </div>
                    <div class="col-auto">
                      
                      <i class="fas fa-truck fa text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
</div>

<hr/>

app/views/pages/dashboard.html.erb
<%= render 'dashboard_header' %>

	
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h4 mb-0 text-gray-800"> Week calendar </h1>
</div>
<div class="col-xl-12 col-md-12 mb-4">           
	<!-- DataTales Example -->
          <div class="card border-left-primary shadow mb-4">
            <div class="card-header py-4">
              <h4 class="m-0  h4 mb-0 text-gray-800"> Date showing: <%= @today_date.strftime("%A %d-%m-%Y") + " - " + @next_friday_date.strftime("%A %d-%m-%Y") %></h4>
              <hr/>
              <p style="margin-top: 10px;">
              <span style="margin-right: 50px;">
              <i class="fas fa-angle-double-left"></i>
              <%= link_to "Previous week", "/pages/dashboard?date=" + @today_date.last_week(:monday).strftime("%Y-%m-%d") %>
            </span>
              <i class="fas fa-angle-left"></i>
              <%= link_to "Previous day", "/pages/dashboard?date=" + @today_date.prev_day.strftime("%Y-%m-%d") %>
              |  <%= link_to "Today", "/pages/dashboard?date=" + DateTime.now.strftime("%Y-%m-%d") %> |

              <span style="margin-right: 50px;">
              <%= link_to "Next day", "/pages/dashboard?date=" + @today_date.next_day.strftime("%Y-%m-%d") %>
              <i class="fas fa-angle-right"></i>
            </span>
             <%= link_to "Next week", "/pages/dashboard?date=" + @today_date.next_occurring(:monday).strftime("%Y-%m-%d") %>
              <i class="fas fa-angle-double-right"></i>
            </p>
            </div>
            <div class="card-body">
              <div id="accordion">
              <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Company</th>
                  <th>How many</th>
                  <th>Delivery date</th>
                  <th>Deliver all</th>
                </tr>
              </thead>
              <tbody>
              <% @companies.each do |c| %>
              
              
                <tr>
                  <td>
                    <button class="btn btn-link" data-toggle="collapse" data-target="#<%=c.short_name%>" aria-expanded="true" aria-controls="<%=c.short_name%>">
                    <%=c.name%>
                    </button>
                  </td>
                  <td>
                    <%= @this_week.where(company_id: c.id).sum(:change_amount) %>
                  </td>
                  <td>
                    <%= @this_week.where(company_id: c.id).first.delivery.strftime("%d-%m-%Y %A") %>
                  </td>
                  
                </tr>
              
              <% end %>
              </tbody>
            </table>
            <hr/>
            <% @companies.each do |c| %>
              <div id="<%=c.short_name%>" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <table class="table table-bordered table-striped"  width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th style="text-decoration: underline;"><%= c.name.upcase %> deliveries</th>
                      <th>Location</th>
                      <th>How many</th>
                      <th>Delivery date</th>
                      <th>Comment</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    <% @this_week.where(company_id: c.id).each do |d| %>
                    <tr>
                      <td><%= link_to d.get_obj.name, d %></td>
                     <td><%= d.get_obj.location %></td>
                     <td><%= d.change_amount %></td>
                      <td><%= d.delivery.strftime("%d-%m-%Y %A") %></td>
                      <td><%= d.got_comments? ? d.get_comment   : "No comments" %>, <%= link_to "Add", new_comment_path + "?klass=" + d.class.name + "&klass_id=" + d.id.to_s  %>   </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
             </div><!-- collapse --> 
            <% end %>
          </div><!-- accordion -->       
        </div>
      </div>
    </div>
  </div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/new_contracts.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"> Choose new contract type </h1>
</div>

<hr/>

<div class="row">
	<div class="col-xl-4 col-md-6 mb-4">
		<!-- Approach -->
	  <div class="card shadow mb-4">
	    <div class="card-header py-3">
	      <h6 class="m-0 font-weight-bold text-primary">
	      Mats
	      </h6>
	    </div>
	    <div class="card-body">
	     <%= link_to new_company_mat_path + "?company_id=" + @company_id.to_s do %>
	     <img src="https://static.wixstatic.com/media/7bdcf9_86edbf74b3ea4deab63eab9b40252a8a~mv2_d_5020_3347_s_4_2.jpg/v1/fill/w_940,h_600,al_c,q_85,usm_0.66_1.00_0.01/ShadowBlueRoll0603.webp" alt="Smiley face" height="300" width="100%">

	     <% end %>
	    </div>
	  </div>
		
	</div>
	<div class="col-xl-4 col-md-6 mb-4">
		<!-- Approach -->
	  <div class="card shadow mb-4">
	    <div class="card-header py-3">
	      <h6 class="m-0 font-weight-bold text-primary">
	      Mops
	      </h6>
	    </div>
	    <div class="card-body">
	    	 <%= link_to new_company_mop_path + "?company_id=" + @company_id.to_s do %>
	    	<img src="https://tekstilvask.no/wp-content/uploads/2016/05/mopper-and-kluter.jpg" alt="Smiley face" height="300" width="100%">
	     	<% end %>
	    </div>
	  </div>
		
	</div>
	<div class="col-xl-4 col-md-6 mb-4">
		<!-- Approach -->
	  <div class="card shadow mb-4">
	    <div class="card-header py-3">
	      <h6 class="m-0 font-weight-bold text-primary">
	      Cloths
	      </h6>
	    </div>
	    <div class="card-body">
	     <img src="https://www.mekk.no/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/0/103994_1.jpg" alt="Smiley face" height="300" width="100%">
	    </div>
	  </div>
		
	</div>

</div>

app/views/pages/one_day.html.erb
<%= render 'dashboard_header' %>

<div class="col-xl-12 col-md-12 mb-4">           
  <!-- DataTales Example -->
          <div class="card  border-left-<%= @color %> shadow mb-4">
            <div class="card-header py-3">
              <h4 class="m-0  h4 mb-0 text-gray-800"> <%= @header  %></h4>
            </div>
            <div class="card-body">
               <div id="accordion">
              <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Company</th>
                  <th>How many</th>
                  <% if @done %>
                  <th>Delivered</th>
                  <% else %>
                  <th>Delivery date</th>
                  <th>Deliver all</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
              <% @companies.each do |c| %>
              
              
                <tr>
                  <td>
                    <button class="btn btn-link" data-toggle="collapse" data-target="#<%=c.short_name%>" aria-expanded="true" aria-controls="<%=c.short_name%>">
                    <%=c.name%>
                    </button>
                  </td>
                  <td>
                    <%= @todays_table.where(company_id: c.id).sum(:change_amount) %>
                  </td>
                  <% if @done %>
                  <td><%= @todays_table.where(company_id: c.id).first.delivered_date.strftime("%d-%m at %H:%m")%></td>
                  <% else %>
                  <td>
                    <%= @todays_table.where(company_id: c.id).first.delivery.strftime("%d-%m-%Y %A") %>
                  </td>
                  
                  <td>
                    <%= link_to "Deliver all", deliver_all_deliveries_path + "?company_id=" + c.id.to_s + "&date=" + @todays_table.first.delivery.strftime("%d-%m-%Y"), :class => "btn btn-success" %>
                  </td>

                  <% end %>
                </tr>
              
              <% end %>
              </tbody>
            </table>
            <hr/>


              <% @companies.each do |c| %>
              <div id="<%=c.short_name%>" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <table class="table table-bordered table-striped" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th style="text-decoration: underline;"><%= c.name.upcase %> deliveries</th>
                      <th>Location</th>
                      <th>How many</th>
                      <th>Delivery date</th>
                      <th>Deliver</th>
                      <th>Delivered</th>
                      <th>Comment</th>
                      <th>Add comment</th>
                    </tr>
                  </thead>
                  
                  <tbody>

                    <% @todays_table.where(company_id: c.id).each do |d| %>
                    <tr>
                
                      <td><%= link_to d.get_obj.name, d %></td>
                      <td><%= d.get_obj.location %></td>
                      <td><%= d.change_amount %></td>
                      
                      <td><%= d.delivery.strftime("%A %d-%m-%Y") %></td>
                      <% if !@is_tomorrow %>
                      <td>
                        <%= form_for d do |form| %>
                          <% if d.delivered?  %>
                                <%= form.hidden_field :delivered, :value => false %>
                                <%= form.submit "Undo" , :class => "btn btn-danger" %>
                          <% else %>
                                 <%= form.hidden_field :delivered, :value => true %>
                                <%= form.submit "Deliver" , :class => "btn btn-success"%>
                          <% end %>
                        <% end %>  

                      </td>
                      <% end %>
                      <td><%= d.delivered? ? d.delivered_date.strftime("%d-%m %H:%m") : "Waiting"  %> </td>
                      <td><%= d.got_comments? ? d.get_comment   : "No comments" %>   </td>
                      <td><%= link_to "Add comment", new_comment_path + "?klass=" + d.class.name + "&klass_id=" + d.id.to_s  %></td>
                    </tr>
                  <% end %>
                 
                    </tbody>
                </table>
                           </div><!-- collapse --> 
            <% end %>
          </div><!-- accordion -->  
            </div>

            
          </div>

app/views/pages/sidebar.html.erb
<!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

 

  
   <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                 <!-- <span class="badge badge-danger badge-counter">3+</span> -->
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>