config/routes.rb
Rails.application.routes.draw do
  resources :company_mops
  resources :mops
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  resources :comments
  resources :deliveries do
    collection do
      get :deliver_all
    end
  end
  
  resources :mats
  
  resources :company_mats
 root :to => 'pages#dashboard'
  resources :companies

resources :pages do 
	collection do 
		get :dashboard
		get :new_contracts
		get :one_day
  end
end
resources :users, only: [:new, :create, :show]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'

   get 'log_out', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :company_mats,  :dependent => :destroy
	has_many :company_mops,  :dependent => :destroy


	def comments
		Comment.where(klass: self.class.name, klass_id: self.id ).order(created_at: :asc)
 
	end


	def short_name
		self.name.delete(" ").downcase
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @comment = Comment.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :street, :post_code, :city, :phone_number, :contact_person, :phone_number_contact_person, :org_nr, :email, :contact_person_email )
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
    
              </div>
              <form class="user">

                 <div class="form-group">
                <%= form.text_field :name, :class => "form-control form-control-user", placeholder: "Company name"%>
                </div>
                <div class="form-group">
                <%= form.text_field :org_nr, :class => "form-control form-control-user", placeholder: "Organization number"%>
                </div>
                 <div class="form-group">
                <%= form.text_field :street, :class => "form-control form-control-user", placeholder: "Street address"%>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                   <%= form.text_field :post_code, :class => "form-control form-control-user", placeholder: "Postal code"%>
                  </div>
                  <div class="col-sm-6">
                   <%= form.text_field :city, :class => "form-control form-control-user", placeholder: "City"%>
                  </div>
                </div>
                 <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                   <%= form.text_field :phone_number, :class => "form-control form-control-user", placeholder: "Phone number"%>
                  </div>
                  <div class="col-sm-6">
                   <%= form.text_field :email, :class => "form-control form-control-user", placeholder: "Company email"%>
                  </div>
                </div>

                <h4 class="m-0  h4 mb-3 text-gray-800">Contact person</h4>
                <div class="form-group row">
                  <div class="col-sm-4 mb-3 mb-sm-0">
                   <%= form.text_field :contact_person, :class => "form-control form-control-user", placeholder: "Contact person"%>
                  </div>
                  <div class="col-sm-4">
                   <%= form.text_field :phone_number_contact_person, :class => "form-control form-control-user", placeholder: "Phone number"%>
                  </div>
                  <div class="col-sm-4">
                   <%= form.text_field :contact_person_email, :class => "form-control form-control-user", placeholder: "Email"%>
                  </div>
                </div>
              
                <%= form.submit "Save", :class => "btn btn-primary btn-user btn-block" %>
              </form>

              
            </div>
          </div>

          <% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Companies</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
          </div>
          <hr/>

 <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">All companies</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Name</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </tfoot>
                  <tbody>

                    <% @companies.each do |company| %>
                    <tr>
                
                      <td><%= link_to company.name, company %></td>
                      <td><%= link_to 'Edit', edit_company_path(company) %></td>
                      <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                 
                    </tbody>
                </table>
              </div>
            </div>
          </div>

app/views/companies/new.html.erb
<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">New Company</h1>
           
          </div>
          <hr/>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"> <%= @company.name %> <small> Org.nr. <%= @company.org_nr %></small> </h1>

    <div class="row">
	    <div class="col">
	    	<i class="far fa-edit"></i>
	           <%= link_to 'Edit company', edit_company_path(@company) %>     

	     	 <i class="far fa-plus-square"></i>
			   <%= link_to "Add new deal", "/pages/new_contracts?company_id=" + @company.id.to_s %>
		</div> 
   	</div>
</div>

<h6 class="m-0  h6 mb-0 text-gray-800"><%= @company.street %></h6>
<h6 class="m-0  h6 mb-0 text-gray-800"><%= @company.post_code %> <%= @company.city %></h6>
<h6 class="m-0  h6 mb-0 text-gray-800"><%= @company.phone_number %></h6>
<h6 class="m-0  h6 mb-0 text-gray-800"> <%= mail_to @company.email do %><i class="fas fa-envelope"></i><% end %></h6>

  

 <hr/>
  <p class="m-0  p mb-0 text-gray-800">
  <b>Contact person: </b><%= @company.contact_person %> <%= mail_to @company.contact_person_email do %><i class="fas  fa-envelope"></i><% end %> <%= @company.phone_number_contact_person %>
  </p>
<hr/>



<!-- Content Row -->
<div class="row">
<% @company.company_mats.each do |m| %>


          
        <div class="col-xl-4 col-lg-6 col-md-12">
            <div class="card border-left-primary shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><%= m.amount %> x <%= m.mat.name %> <%= "mat".pluralize(m.amount) %>  </h6>
              </div>
              <div class="card-body">
                  		<p><strong>Change every </strong>
        						  <%= m.change_day %>, <%= m.change %> <%= "time".pluralize(m.change) %> a month
        						  </p>
                      <p><strong>Location </strong>
                      <%= m.location %>
                      </p>

        						<table class="table table-dark table-striped">
                      <thead>
                        <tr>
                        <th style="width: 50%;font-weight: 500">Pr. mat</th>
                        <th style=" font-weight: 500">Pr. month</th>
                      </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td><%= m.contract_price %>kr</td>
                          <td><%= m.month_price %>kr</td>
                        </tr>
                        <tr>
                          <th style="width: 50%; font-weight: 500;">Pr. delivery</th>
                          <th style="font-weight: 500;">Pr. month</th>
                        </tr>
                        <tr>
                          <td><%= m.delivery_price %>kr</td>
                          <td><%= m.delivery_m_price %>kr</td>
                        </tr>
                         <tr>
                          <th>SUM</th>
                          <th><%= m.month_sum %>kr</th>
                        </tr>
                      </tbody>      
                    </table>
                      <p>
                      <strong>Period</strong>
                      <%= m.start_date.strftime("%a %d-%m-%Y") %> - <%= m.end_date.strftime("%a %d-%m-%Y") %>
                    </p>
                    
            	</div>
              <div class="card-footer">
                <i class="far fa-edit"></i>
                <%= link_to "Edit contract", edit_company_mat_path(m) %> 
                <i class="far fa-minus-square"></i>
                <%= link_to 'Delete', m, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
                    
                  
          </div>
      </div>

 <% end -%>

 </div>
<hr/>
 <h3 class="h3 mb-3 text-gray-800">Comments </h3>
 <% @company.comments.each do |c| %>
<div class="row-fluid">
<div class="col-xl-6 col-lg-12 col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Karl Andre Oddsen <small style="float:right"><%= c.created_at.strftime("%d-%m-%Y %H:%M") %></small></h6>
              </div>
              <div class="card-body py-1">
                    <p class="text-italic">
                      <%= c.comment %>
                    </p>
                    
              </div>
              <div class="card-footer">
                <i class="far fa-edit"></i>
                <%= link_to "Edit", edit_comment_path(c) %> 
                <i class="far fa-minus-square"></i>
                <%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
                    
                  
          </div>
      </div>
</div>

<% end %>
  
<hr/>
<div class="row-fluid">
  <div class="col-xl-8 col-lg-12 col-md-12">
              <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text"> Add comment</h6>
                </div>
                <div class="card-body py-1" style="width: 100%" >
                   <%= form_for @comment do |form| %>
                    <%= form.hidden_field :klass, :value => @company.class.name  %>
                    <%= form.hidden_field :klass_id, :value => @company.id  %>
                    <%= form.text_area :comment, size: "65%", placeholder: "Write comment here" %> 
                      
                </div>
                <div class="card-footer">
                 <%= form.submit "Comment", :class => "btn btn-primary btn-block"  %>
                 <% end %> 
                </div>
                      
                    
            </div>
    </div>
</div>