config/routes.rb
Rails.application.routes.draw do
  resources :company_mops
  resources :mops
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  resources :comments
  resources :deliveries do
    collection do
      get :deliver_all
    end
  end
  
  resources :mats
  
  resources :company_mats
 root :to => 'pages#dashboard'
  resources :companies

resources :pages do 
	collection do 
		get :dashboard
		get :new_contracts
		get :one_day
  end
end
resources :users, only: [:new, :create, :show]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'

   get 'log_out', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_footer.html.erb
 <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Rogamatter.no 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->
</div>
  
  <!-- Bootstrap core JavaScript-->
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/js/sb-admin-2.min.js"></script>

  <!-- Page level plugins -->
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/js/demo/datatables-demo.js"></script>


  </body>
</html>

app/views/layouts/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rogamatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      
  <!-- Custom fonts for this template-->
  <link href="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet">
  <link href="https://StartBootstrap.github.io/startbootstrap-sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
   <div id="wrapper">
    

app/views/layouts/partials/_nav_bar.html.erb
   <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <%= link_to "/pages/dashboard" do %>
      <span class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Rogamatter <sup>admin</sup></div>
      </span>
     <% end -%>
      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <%= link_to "/pages/dashboard" do %>
        <span class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>

          <span>Dashboard</span></span>
        <% end %>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Meny
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCompany" aria-expanded="true" aria-controls="collapseCompany">
          <i class="fas fa-building"></i>
          <span>Companies </span>
        </a>
        <div id="collapseCompany" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
           <!-- <h6 class="collapse-header">Edit companies :</h6>-->
             <%= link_to companies_path do %>
             <span class="collapse-item">
               All companies
            </span>
             <% end -%>
             <%= link_to new_company_path do %>
             <span class="collapse-item">
              <i class="fas fa-plus fa-sm fa-fw mr-2 "></i>
               Add new company
            </span>
             <% end -%>
            
        
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseContract" aria-expanded="true" aria-controls="collapseContract">
          <i class="far fa-edit"></i>
          <span>Contracts</span>
        </a>
        <div id="collapseContract" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
             <%= link_to company_mats_path do %>
             <span class="collapse-item">
               All contracts
            </span>
             <% end -%>
             <%= link_to new_company_mat_path do %>
             <span class="collapse-item">
              <i class="fas fa-plus fa-sm fa-fw mr-2 "></i>
               New contract
            </span>
             <% end -%>
           
          </div>
        </div>
      </li>

       <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMat" aria-expanded="true" aria-controls="collapseMat">
          <i class="fas fa-money-bill-wave-alt"></i>
          <span>Mats</span>
        </a>
        <div id="collapseMat" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
             <%= link_to mats_path do %>
             <span class="collapse-item">
               All mats
            </span>
             <% end -%>
             <%= link_to new_mat_path do %>
             <span class="collapse-item">
              <i class="fas fa-plus fa-sm fa-fw mr-2 "></i>
               New mat
            </span>
             <% end -%>
           
          </div>
        </div>
      </li>
 <!--
       <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMop" aria-expanded="true" aria-controls="collapseMat">
          <i class="fas fa-money-bill-wave-alt"></i>
          <span>Mops</span>
        </a>
        <div id="collapseMop" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
             <%= link_to mops_path do %>
             <span class="collapse-item">
               All mops
            </span>
             <% end -%>
             <%= link_to new_mop_path do %>
             <span class="collapse-item">
              <i class="fas fa-plus fa-sm fa-fw mr-2 "></i>
               New mop
            </span>
             <% end -%>
           
          </div>
        </div>
      </li>
-->
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseDelivery" aria-expanded="true" aria-controls="collapseCompany">
         <i class="fas fa-truck "></i>
          <span>Deliveries </span>
        </a>
        <div id="collapseDelivery" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
           <!-- <h6 class="collapse-header">Edit companies :</h6>-->
             <%= link_to "/pages/one_day?done=true&day=today" do %>
             <span class="collapse-item">
              <i class="fas fa-check fa-sm fa-fw mr-2 "></i>
               Done today
            </span>
             <% end -%>
             <%= link_to "/pages/one_day?done=false&day=today" do %>
             <span class="collapse-item">
              <i class="fas fa-times fa-sm fa-fw mr-2 "></i>
               To make today
            </span>
             <% end -%>
            <%= link_to "/pages/one_day?done=false&day=tomorrow" do %>
             <span class="collapse-item">
              <i class="fas fa-exclamation fa-sm fa-fw mr-2 "></i>
               To make tomorrow
            </span>
             <% end -%>
          
          </div>
        </div>
      </li>

      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>


    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
<% if current_user %>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

         

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                
                <i class="far fa-comments fa-2x"></i>
                <!-- Counter - Messages -->
                <!-- <span class="badge badge-danger badge-counter">7</span> -->
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Recent comments
                </h6>

                <% Comment.order("created_at desc").limit(4).each do |c| %>
                <%= link_to Comment.first, :class => "dropdown-item d-flex align-items-center" do %>
                
                    <div class="dropdown-list-image mr-3">
                      <i class="fas fa-user-alt fa-3x rounded-circle"></i>
                     <% if user_logged_id(c.user) %>
                      <div class="status-indicator bg-success"></div>
                      <% end %>
                    </div>
                    <div class="font-weight-bold">
                      <div class="text-truncate"><%= c.comment %></div>
                      <div class="small text-gray-700"><%= c.user.username %> · <%= time_ago_in_words(c.created_at) %></div>  
                    </div>
                  <% end %>
                <% end %>
                <%= link_to "Read More Comments", comments_path, :class => "dropdown-item text-center small text-gray-700" %>
                 
                
                
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 "><%= current_user.username %></span>
                <i class="far fa-user fa-2x"></i>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <%= link_to '/log_out', :class => "dropdown-item" do  %>
                <i class="fas fa-sign-out-alt"></i>
                  
                  Logout
                
                <% end %>
              </div>
            </li>

          </ul>

        </nav>

<% end %>
        <!-- End of Topbar -->